name: Day 4 GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  learning:
  runs-on: ubuntu-latest

steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Say hello
        run: echo "Hello from Day 4!"

      - name: Show repository
        run: echo "Repository: ${{ github.repository }}"

      - name: Show branch
        run: echo "Branch: ${{ github.ref }}"
